services:
  nginx:
    build: nginx/.
    ports:
    - 8443:8443
    depends_on:
    - mailcrab
    - rauthy

  mailcrab:
    image: marlonb/mailcrab:latest
    environment:
    - MAILCRAB_PREFIX=mail
    ports:
    - 1080:1080

  rauthy:
    image: ghcr.io/sebadob/rauthy:latest
    environment:
      - LOCAL_TEST=true
      - SMTP_URL=mailcrab
      - SMTP_PORT=1025
      - SMTP_DANGER_INSECURE=true
      - SMTP_USERNAME=test
    volumes:
      - data:/app/data
#    ports:
#      - "8443:8443"
    depends_on:
      - mailcrab

volumes:
  data:

