services:
  nginx:
    build: nginx/.
    ports:
    - 8443:8443
    depends_on:
    - mailcrab
    - oidc-toolkit

  mailcrab:
    image: marlonb/mailcrab:latest
    environment:
    - MAILCRAB_PREFIX=mail
    ports:
    - 1080:1080

  oidc-toolkit:
    image: ghcr.io/businesssimulations/dev-oidc-toolkit:latest
    environment:
      - ASPNETCORE_URLS=http://+:8443/auth/
      - DevOidcToolkit__Port=8443
      - DevOidcToolkit__Database__SqliteFile=/app/data/oidc-toolkit.db
      - DevOidcToolkit__Users__0__Email=test@localhost
      - DevOidcToolkit__Users__0__FirstName=Test
      - DevOidcToolkit__Users__0__LastName=User
      - DevOidcToolkit__Users__1__Email=test2@localhost
      - DevOidcToolkit__Users__1__FirstName=Test2
      - DevOidcToolkit__Users__1__LastName=User2
      - DevOidcToolkit__Clients__0__Id=client
      - DevOidcToolkit__Clients__0__Secret=secret
      - DevOidcToolkit__Clients__0__RedirectUris__INDEX=http://localhost:3000/auth/callback
    volumes:
      - data:/app/data
    depends_on:
      - mailcrab

volumes:
  data:

