user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen 8443 ssl;

        ssl_certificate /certs/cert.crt;
        ssl_certificate_key /certs/cert.key;

        # ssl_protocols TLSv1.2 TLSv1.3;
        # ssl_ciphers HIGH:!aNULL:!MD5;

        server_name  localhost;
        absolute_redirect off;

        location /mail {
            proxy_set_header Host localhost;
            proxy_pass http://mailcrab:1080;
            add_header test "mail";
        }

        location /mail/ {
            proxy_pass http://mailcrab:1080;
            proxy_set_header Host localhost;
            add_header test "directoried";
        }

        location /auth/ {
            proxy_pass "http://oidc-toolkit:8443/";
            proxy_set_header Host localhost;
            proxy_ssl_verify off;
            proxy_redirect http://localhost/ /auth/;
            proxy_redirect / /auth/;
            sub_filter "href=\"/" "href=\"/auth/";
            sub_filter "https://localhost:8443" "https://localhost:8443/auth/";
            sub_filter "http://localhost" "https://localhost:8443/auth/";
            sub_filter_once off;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

}
